# Your Wi-Fi SSID and password
wifi_ssid: "myWifi"
wifi_password: "myPassword"
# API Key for encryption
api_key: "32ByteBase64EncodedApiKey" # see & gen key on https://esphome.io/components/api.html
# credentials for webui access
web_username: "admin"
web_password: "tynet.eu"
hcp_wifi_ap_password: "tynet.eu"